#!/bin/bash

rails generate model Question contenido:text user_id:integer faculty_id:integer num_visitas:integer mejor_respuesta:integer
rails generate model Answer contenido:text question_id:integer user_id:integer
rails generate model QuestionComment contenido:text question_id:integer user_id:integer
rails generate model AnswerComment contenido:text answer_id:integer user_id:integer
rails generate model Label nombre
rails generate model AnswerVote tipo:boolean user_id:integer answer_id:integer
rails generate model QuestionVote tipo:boolean user_id:integer question_id:integer
rails generate model QuestionCommentVote tipo:boolean user_id:integer question_id:integer
rails generate model AnswerCommentVote tipo:boolean user_id:integer answer_comment_id:integer
rails generate model Level nombre puntos:integer
rails generate model Faculty nombre direction_id:integer
rails generate model User nombre apellido mail puntos:integer pass level_id:integer faculty_id:integer
rails generate model Direction ciudad calle
rails generate model QuestionLabel question_id:integer label_id:integer

rails g migration RemoveQuestion_idFromQuestion_comment_votes question_id:integer
rails g migration Add_question_commet_id_to_question_comment_votes question_comment_id:integer

rails g migration Add_admin_to_user admin:boolean

rails g migration Add_activo_to_user activo:boolean
rails g migration Add_activo_to_faculty activo:boolean
rails g migration Add_activo_to_label activo:boolean
rails g migration Add_activo_to_level activo:boolean
rails g migration Add_activo_to_direction activo:boolean
