#!/bin/bash

rails generate model Question contenido:string
rails generate model Answer contenido:string
rails generate model Comment contenido:string
rails generate model Label nombre:string
rails generate model AnswerVote tipo:boolean
rails generate model QuestionVote tipo:boolean
rails generate model CommentVote tipo:boolean
rails generate model Level nombre:string puntos:integer
rails generate model Faculty nombre:string
rails generate model User nombre:string apellido:string mail:string puntos:integer pass:string
rails generate model Direction ciudad:string calle:string
